#!/bin/bash

sv d /etc/runit/runsvdir/default/srk-ua-responder
sv d /etc/runit/runsvdir/default/srk-ua-helper
sv d /etc/runit/runsvdir/default/srk-ua-rssh

rm -rf /etc/runit/runsvdir/default/srk-ua-responder
rm -rf /etc/runit/runsvdir/default/srk-ua-helper
rm -rf /etc/runit/runsvdir/default/srk-ua-rssh

[ -L /etc/apache2/sites-enabled/sark  ] && a2dissite sark.conf
[ -L /etc/apache2/sites-available/sark  ] && rm -rf /etc/apache2/sites-available/sark
#Jessie 
[ -L /etc/apache2/sites-enabled/sark.conf  ] && a2dissite sark.conf
[ -L /etc/apache2/sites-available/sark.conf  ] && rm -rf /etc/apache2/sites-available/sark.conf
[ -L /etc/apache2/sites-enabled/sark-ssl.conf  ] && a2dissite sark-ssl.conf
[ -L /etc/apache2/sites-available/sark-ssl.conf  ] && rm -rf /etc/apache2/sites-available/sark-ssl.conf

[ -L /etc/service/sark ] && rm -rf /etc/service/sark
[ -L /etc/service/srk-ua-responder ] && rm -rf /etc/service/srk-ua-responder
[ -L /etc/service/srk-ua-helper ] && rm -rf /etc/service/srk-ua-helper

[ -L /etc/fail2ban/jail.local ] && rm -rf /etc/fail2ban/jail.local
[ -L /etc/fail2ban/action.d/shorewall.local ] && rm -rf /etc/fail2ban/action.d/shorewall.local
[ -L /etc/fail2ban/filter.d/asterisk.conf ] && rm -rf /etc/fail2ban/filter.d/asterisk.conf 

[ -e /etc/sudoers.d/sarkrssh ] && rm -rf /etc/sudoers.d/sarkrssh 

# stretch teardown
grep -q '^9\.' /etc/debian_version 
if [  "$?" -eq "0" ] ; then	
	systemctl disable  debsetlan
fi	
# jessie teardown
grep -q '^8\.' /etc/debian_version 
if [  "$?" -eq "0" ] ; then	
	[ -e /etc/init.d/debsetlan ] && rm -rf /etc/init.d/debsetlan
fi
# wheezy teardown
grep -q '^7\.' /etc/debian_version 
if [  "$?" -eq "0" ] ; then	
	[ -e /etc/init.d/debsetlan ] && rm -rf /etc/init.d/debsetlan
fi