<?php
//
// Generated file warning
//
$OUT = <<<BANNEREND
;
;               DO NOT MODIFY THIS FILE
; It is generated by the SARK/SAIL Asterisk generator code and
; it will be overwritten each time you issue a COMMIT in the
; SARK/SAIL GUI workbench.
;

BANNEREND;
?>
