UPDATE globals SET LDAPBASE='dc=sark,dc=aelintra,dc=com' WHERE LDAPBASE IS NULL;
UPDATE globals SET LDAPOU='contacts' WHERE LDAPOU IS NULL;
UPDATE globals SET LDAPUSER='admin' WHERE LDAPUSER IS NULL;
UPDATE globals SET LDAPPASS='sarkroot' WHERE LDAPPASS IS NULL;
