#!/bin/bash
[ ! -e /opt/sark/db/sark.db ] && exit 4

/usr/bin/logger Regenerating Asterisk

php /opt/sark/generator/runApacheGen.php

# HA
if [ -e "/etc/ha.d" ]; then
        /usr/bin/php /opt/sark/generator/sarkha.php >/dev/null
fi
# copy the DB
/bin/cp /opt/sark/db/sark.db /opt/sark/db/sark.copy.db
/bin/mv /opt/sark/db/sark.copy.db /opt/sark/db/sark.rdonly.db
#
/usr/bin/logger Regenerating Asterisk Finished
#/usr/bin/sqlite3 /opt/sark/db/sark.db "UPDATE globals SET MYCOMMIT='NO' WHERE pkey='global';"
