#!/bin/bash

sv d srk-ua-responder
sv d srk-ua-helper

rm -rf /etc/apache2/sites-enabled/sark*
rm -rf /etc/apache2/sites-available/sark*

[ -L /etc/cron.d/sark ] && rm -rf /etc/cron.d/sark

rm -rf /etc/service/srk*

[ -L /etc/fail2ban/jail.local ] && rm -rf /etc/fail2ban/jail.local
[ -L /etc/fail2ban/action.d/shorewall.local ] && rm -rf /etc/fail2ban/action.d/shorewall.local
[ -L /etc/fail2ban/filter.d/asterisk.conf ] && /etc/fail2ban/filter.d/asterisk.conf 

[ -e /etc/sudoers.d/sarkrssh ] && rm -rf /etc/sudoers.d/sarkrssh 

systemctl disable  debsetlan
