#!/bin/sh
#
#	script to merge/move sound recordings 
#

	test ! $1 && echo "NO P1!" && exit 4
#	test ! $2 && echo "NO P2"  && exit 4

	LEFT="$1" 
	RIGHT="$2"
	OUT="$3"

	SOX=`/usr/bin/which sox`
	NICE=`/usr/bin/which nice`
        MONITOROUT=/var/spool/asterisk/monout
	MONITORSTAGE=/var/spool/asterisk/monstage
	if [ -e /persistent ]; then 
		MONITORSTAGE=/var/spool/asterisk/monout
	fi
	if [ -e /opt/sark/.noqueues ]; then
		MONITORSTAGE=/var/spool/asterisk/monout
	fi

#	echo "LEFT IS $LEFT"
#	echo "RIGHT IS $RIGHT"
#	echo "OUT IS $OUT"

#	/usr/bin/test ! -r $RIGHT && exit 22

	if [ "$LEFT" = "mixmon" ]; then
#		echo "MOVING MIXMON $RIGHT"
		if [ -e /opt/sark/otrr/$RIGHT ]; then
			/bin/rm -rf /opt/sark/otrr/$RIGHT
			/usr/bin/test ! -r  /opt/sark/.recone && exit 0
			/bin/mv $RIGHT $MONITOROUT
			exit 0
		fi
		if [ -e /opt/sark/mixmon/$RIGHT ]; then
			/bin/rm -rf /opt/sark/mixmon/$RIGHT
			/usr/bin/test ! -r $RIGHT && exit 22
			/bin/mv $RIGHT $MONITOROUT
			exit 0
		fi
		echo "Removing unwanted mixmon $RIGHT"
        	rm -rf $RIGHT
		exit 0
	fi
	
#	echo "MERGE/MOVE MONITOR"
	/usr/bin/test ! -r $LEFT && exit 21
	$NICE $SOX -m -v 1 $LEFT -v 1 $RIGHT  $OUT
	/usr/bin/test  -r $OUT && rm -rf $LEFT $RIGHT
#	/usr/bin/test ! -r  /opt/sark/.recone && exit 0 
	/bin/mv $OUT $MONITORSTAGE
#	/bin/rm -rf /home/sark/$OUT
	exit 0
# eof
