#!/bin/bash
/bin/ps -e  | /bin/grep asterisk | /bin/grep -v grep > /dev/null 2>&1
if [ "$?" -ne "0" ]; then
        /bin/logger RELOAD requested but Asterisk is not running
	exit 1
fi
/bin/logger Reloading Asterisk
/usr/bin/php /opt/sark/generator/astreload.php
#/bin/sleep 1
/bin/logger Reloading Asterisk Finished


