<?php
// +-----------------------------------------------------------------------+
// |  Copyright (c) CoCoSoft 2005-10                                  |
// +-----------------------------------------------------------------------+
// | This file is free software; you can redistribute it and/or modify     |
// | it under the terms of the GNU General Public License as published by  |
// | the Free Software Foundation; either version 2 of the License, or     |
// | (at your option) any later version.                                   |
// | This file is distributed in the hope that it will be useful           |
// | but WITHOUT ANY WARRANTY; without even the implied warranty of        |
// | MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the          |
// | GNU General Public License for more details.                          |
// +-----------------------------------------------------------------------+
// | Author: CoCoSoft
// +-----------------------------------------------------------------------+
//
include("localvars.php");

$mailbox = array();
$parts=array();

$file = '/etc/asterisk/voicemail.conf' or die('Could not read file!');
if (file_exists($file)) {
    $rec = file($file) or die('Could not read file!');
     foreach ($rec as $line) {
		$line = trim ($line);
		if (!preg_match(" /^;.*/",$line)) {
			$line = preg_replace( '/\s+/', ' ', $line );
			if (preg_match(" /^(\d{3,4})\s*=>\s*((\d*)?),/",$line,$matches)) {			
				$mailbox[$matches[1]]['password'] = $matches[2];
			}
			$parts = explode('=>',$line);
			if (isset($parts[1])) {	
				$exten = trim($parts[0]);		
				$params = explode(',',$parts[1]);
				if (isset($params[1])) {
					$mailbox[$exten]['name'] = trim($params[1]);
				}
				if (isset($params[2])) {
					$mailbox[$exten]['email'] = trim($params[2]);
				}
				if (isset($params[3])) {
					$mailbox[$exten]['options'] = trim($params[3]);
				}
				if (isset($params[4])) {
					$mailbox[$exten]['options'] .= ',' . trim($params[4]);
				}								
			}				
		}
    }
	
}
	$fh = fopen("/etc/asterisk/voicemail.conf", 'w') or die('Could not open file!');
     
	fwrite($fh, "#include sark_vmail_header.conf  \n" .
				"#include sark_customer_vmail_header.conf  \n" .
				"#include sark_vmail_layout.conf \n")
//				"#include sark_vmail_main.conf  \n" .
// 				"#include sark_customer_vmail_main.conf  \n") 
		or die('Could not write to file');
//
// Generated file warning
//

$OUT = <<<BANNEREND
;
;               Modifying this file
; This file is generated by the SARK/SAIL Asterisk generator code and
; it will be overwritten each time you issue a COMMIT in the
; SARK/SAIL GUI workbench.  However, it will preserve changes to the voicemail
; passwords provided you use passwords of either three or four digits and you 
; can also supply an options statement at the end of each mailbox stanza.
;

BANNEREND;


$OUT .=	"[default]\n";
try {
    /*** connect to SQLite database ***/
    $dbh = new PDO($sarkdb);

    /*** set the error reporting attribute ***/
    $dbh->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

    $sql = "SELECT * FROM IPphone order by pkey";

    foreach ($dbh->query($sql) as $row) {
		if ($row['dvrvmail'] != 'None') {
			if (isset ($mailbox[$row['pkey']]['password'])) {
				$pwd = $mailbox[$row['pkey']]['password'];
			}
			else {
				$pwd = $row['pkey']	;
			}
			$OUT .= $row['pkey'] . ' => ' . $pwd . ',' . $row['desc'] . ',' .
			$row['vmailfwd'];
			if (isset($mailbox[$row['pkey']]['options'])) {
				$OUT .= ',' . $mailbox[$row['pkey']]['options'];
			}
			$OUT .= " \n";
        }
    }
    /*** close the database connection ***/
    $dbh = null;
	 


	fwrite($fh,$OUT) or die('Could not write to file');
	fclose($fh); 


}
catch(PDOException $e)
    {
    echo $e->getMessage();
    }
?>
